export const VotingActions = {
  CREATE_ELECTION: "CREATE_ELECTION",
  NOMINATE_CANDIDATE: "NOMINATE_CANDIDATE",
  CAST_VOTE: "CAST_VOTE",
  UPDATE_USER_DATA: "UPDATE_USER_DATA",
  UPDATE_ELECTION_DATA: "UPDATE_ELECTION_DATA",
  SET_ERROR: "SET_ERROR",
  SET_LOADING: "SET_LOADING",
};